/* AUTO-GENERATED by tools/build.py - is file ko hath se edit na karein, tools/projects.json edit karein */
window.TECH = {
  "wordpress": {
    "name": "WordPress",
    "color": "#21759b",
    "short": "Wp"
  },
  "shopify": {
    "name": "Shopify",
    "color": "#5e8e3e",
    "short": "Sh"
  },
  "laravel": {
    "name": "Laravel",
    "color": "#ff2d20",
    "short": "La"
  },
  "react": {
    "name": "React",
    "color": "#149eca",
    "short": "Re"
  },
  "aspnet": {
    "name": "ASP.NET Core",
    "color": "#512bd4",
    "short": ".N"
  },
  "angular": {
    "name": "Angular",
    "color": "#dd0031",
    "short": "Ng"
  }
};
window.PROJECTS = [
  {
    "slug": "fashion-store-shopify",
    "title": "Urban Threads - Fashion Store",
    "category": "shopify",
    "tags": [
      "Liquid",
      "Shopify 2.0",
      "JavaScript",
      "SCSS"
    ],
    "year": 2025,
    "client": "Urban Threads",
    "summary": "Custom Shopify 2.0 theme with quick-view, size guide and ajax cart for a fashion brand.",
    "featured": true,
    "url": "projects/fashion-store-shopify/index.html",
    "thumb": "projects/fashion-store-shopify/thumbnail.svg"
  },
  {
    "slug": "gadget-hub-shopify",
    "title": "Gadget Hub - Electronics Store",
    "category": "shopify",
    "tags": [
      "Liquid",
      "Shopify Apps",
      "Klaviyo"
    ],
    "year": 2024,
    "client": "Gadget Hub",
    "summary": "Electronics store with product comparison, bundles and email automation.",
    "featured": false,
    "url": "projects/gadget-hub-shopify/index.html",
    "thumb": "projects/gadget-hub-shopify/thumbnail.svg"
  },
  {
    "slug": "corporate-site-wordpress",
    "title": "Nexa Corp - Corporate Website",
    "category": "wordpress",
    "tags": [
      "WordPress",
      "Elementor",
      "PHP",
      "ACF"
    ],
    "year": 2025,
    "client": "Nexa Corporation",
    "summary": "Fast multilingual corporate website with custom post types and ACF blocks.",
    "featured": true,
    "url": "projects/corporate-site-wordpress/index.html",
    "thumb": "projects/corporate-site-wordpress/thumbnail.svg"
  },
  {
    "slug": "woocommerce-grocery",
    "title": "FreshCart - WooCommerce Grocery",
    "category": "wordpress",
    "tags": [
      "WooCommerce",
      "PHP",
      "REST API",
      "MySQL"
    ],
    "year": 2024,
    "client": "FreshCart",
    "summary": "Online grocery with delivery slots, area-wise pricing and custom checkout.",
    "featured": false,
    "url": "projects/woocommerce-grocery/index.html",
    "thumb": "projects/woocommerce-grocery/thumbnail.svg"
  },
  {
    "slug": "school-management-laravel",
    "title": "EduPro - School Management System",
    "category": "laravel",
    "tags": [
      "Laravel 11",
      "MySQL",
      "Bootstrap",
      "Livewire"
    ],
    "year": 2025,
    "client": "EduPro Schools",
    "summary": "Multi-branch school ERP: students, fees, attendance, exams and parent portal.",
    "featured": true,
    "url": "projects/school-management-laravel/index.html",
    "thumb": "projects/school-management-laravel/thumbnail.svg"
  },
  {
    "slug": "crm-api-laravel",
    "title": "LeadFlow - CRM & REST API",
    "category": "laravel",
    "tags": [
      "Laravel",
      "REST API",
      "Sanctum",
      "Redis"
    ],
    "year": 2024,
    "client": "LeadFlow",
    "summary": "CRM backend with REST API, queues, webhooks and role-based dashboards.",
    "featured": false,
    "url": "projects/crm-api-laravel/index.html",
    "thumb": "projects/crm-api-laravel/thumbnail.svg"
  },
  {
    "slug": "ecommerce-react",
    "title": "ShopSphere - React Storefront",
    "category": "react",
    "tags": [
      "React",
      "Redux Toolkit",
      "Tailwind",
      "Stripe"
    ],
    "year": 2025,
    "client": "ShopSphere",
    "summary": "Headless e-commerce storefront with cart, wishlist and Stripe checkout.",
    "featured": true,
    "url": "projects/ecommerce-react/index.html",
    "thumb": "projects/ecommerce-react/thumbnail.svg"
  },
  {
    "slug": "analytics-dashboard-react",
    "title": "InsightBoard - Analytics Dashboard",
    "category": "react",
    "tags": [
      "React",
      "TypeScript",
      "Recharts",
      "Vite"
    ],
    "year": 2024,
    "client": "InsightBoard",
    "summary": "Realtime analytics dashboard with charts, filters and export options.",
    "featured": false,
    "url": "projects/analytics-dashboard-react/index.html",
    "thumb": "projects/analytics-dashboard-react/thumbnail.svg"
  },
  {
    "slug": "hr-portal-aspnet",
    "title": "PeopleHub - HR & Payroll Portal",
    "category": "aspnet",
    "tags": [
      "ASP.NET Core 8",
      "C#",
      "SQL Server",
      "EF Core"
    ],
    "year": 2025,
    "client": "PeopleHub",
    "summary": "HR system with payroll, leave management, attendance and employee self-service.",
    "featured": true,
    "url": "projects/hr-portal-aspnet/index.html",
    "thumb": "projects/hr-portal-aspnet/thumbnail.svg"
  },
  {
    "slug": "inventory-api-aspnet",
    "title": "StockMate - Inventory Web API",
    "category": "aspnet",
    "tags": [
      "ASP.NET Core Web API",
      "JWT",
      "Dapper",
      "Swagger"
    ],
    "year": 2024,
    "client": "StockMate",
    "summary": "Inventory and POS API with JWT auth, Swagger docs and background jobs.",
    "featured": false,
    "url": "projects/inventory-api-aspnet/index.html",
    "thumb": "projects/inventory-api-aspnet/thumbnail.svg"
  },
  {
    "slug": "erp-frontend-angular",
    "title": "OpsCenter - ERP Frontend",
    "category": "angular",
    "tags": [
      "Angular 17",
      "RxJS",
      "NgRx",
      "Angular Material"
    ],
    "year": 2025,
    "client": "OpsCenter",
    "summary": "Modular ERP frontend with lazy-loaded modules, NgRx store and role-based UI.",
    "featured": true,
    "url": "projects/erp-frontend-angular/index.html",
    "thumb": "projects/erp-frontend-angular/thumbnail.svg"
  },
  {
    "slug": "booking-app-angular",
    "title": "BookIt - Appointment Booking",
    "category": "angular",
    "tags": [
      "Angular",
      "TypeScript",
      "Firebase",
      "PWA"
    ],
    "year": 2024,
    "client": "BookIt",
    "summary": "PWA booking app with realtime availability and push notifications.",
    "featured": false,
    "url": "projects/booking-app-angular/index.html",
    "thumb": "projects/booking-app-angular/thumbnail.svg"
  }
];
